In [1]:
import requests

import pandas as pd

In [2]:
base_url = 'https://data.cityofnewyork.us'
electronics = '/resource/wshr-5vic.json'
params = {
    "$select": "dropoff_sitename, address, borough, zipcode, latitude, longitude"
}

rE = requests.get(base_url + electronics, params = params)

In [4]:
rE

In [5]:
electronics = rE.json()

In [6]:
electronics

[{'dropoff_sitename': 'Best Buy',
  'address': '8923 Bay Pkwy',
  'borough': 'Brooklyn',
  'zipcode': '11214',
  'latitude': '40.59360561',
  'longitude': '-73.99907225'},
 {'dropoff_sitename': 'Recycle Your Devices',
  'address': '1885 Victory Blvd',
  'borough': 'Staten Island',
  'zipcode': '10314',
  'latitude': '40.61714326',
  'longitude': '-74.12507436'},
 {'dropoff_sitename': 'WE Pickups LLC',
  'address': '432 Austin Place #408',
  'borough': 'Bronx',
  'zipcode': '10455',
  'latitude': '40.8090356',
  'longitude': '-73.9053482'},
 {'dropoff_sitename': 'Apple Store',
  'address': '2655 Richmond Ave',
  'borough': 'Staten Island',
  'zipcode': '10314',
  'latitude': '40.58187',
  'longitude': '-74.165866'},
 {'dropoff_sitename': 'Staples',
  'address': '90-30 Metropolitan Ave',
  'borough': 'Queens',
  'zipcode': '11374',
  'latitude': '40.71103454',
  'longitude': '-73.85841309'},
 {'dropoff_sitename': 'Staples',
  'address': '5-9 Union Square W',
  'borough': 'Manhattan',
  'zipcode': '10003',
  'latitude': '40.7354498',
  'longitude': '-73.9915753'},
 {'dropoff_sitename': 'Goodwill',
  'address': '44 W 8 St',
  'borough': 'Manhattan',
  'zipcode': '10011',
  'latitude': '40.732951',
  'longitude': '-73.998643'},
 {'dropoff_sitename': 'Salvation Army',
  'address': '208 8 Ave',
  'borough': 'Manhattan',
  'zipcode': '10011',
  'latitude': '40.743678',
  'longitude': '-73.999235'},
 {'dropoff_sitename': 'Staples',
  'address': '251-21 Jericho Turnpike',
  'borough': 'Queens',
  'zipcode': '11426',
  'latitude': '40.72765982',
  'longitude': '-73.71333697'},
 {'dropoff_sitename': 'Salvation Army',
  'address': '6822 3 Ave',
  'borough': 'Brooklyn',
  'zipcode': '11220',
  'latitude': '40.6362001',
  'longitude': '-74.0260663'},
 {'dropoff_sitename': 'Staples',
  'address': '24-41 31 St',
  'borough': 'Queens',
  'zipcode': '11102',
  'latitude': '40.77122118',
  'longitude': '-73.91629611'},
 {'dropoff_sitename': 'J&J Recycling',
  'address': '1641 Richmond Terrace',
  'borough': 'Staten Island',
  'zipcode': '10310',
  'latitude': '40.6403145',
  'longitude': '-74.1212432'},
 {'dropoff_sitename': 'Staples',
  'address': '5110 Broadway',
  'borough': 'Queens',
  'zipcode': '11377',
  'latitude': '40.7538623',
  'longitude': '-73.9089981'},
 {'dropoff_sitename': 'Staples',
  'address': '348 4th Ave',
  'borough': 'Brooklyn',
  'zipcode': '11215',
  'latitude': '40.67418233',
  'longitude': '-73.98677487'},
 {'dropoff_sitename': 'Salvation Army',
  'address': '436 Atlantic Ave',
  'borough': 'Brooklyn',
  'zipcode': '11217',
  'latitude': '40.6863101',
  'longitude': '-73.9838984'},
 {'dropoff_sitename': 'Apple Store',
  'address': '123 Flatbush Ave',
  'borough': 'Brooklyn',
  'zipcode': '11217',
  'latitude': '40.686202',
  'longitude': '-73.978499'},
 {'dropoff_sitename': 'Goodwill',
  'address': '258 Livingston St',
  'borough': 'Brooklyn',
  'zipcode': '11201',
  'latitude': '40.6887457',
  'longitude': '-73.9842131'},
 {'dropoff_sitename': 'Best Buy',
  'address': '369 Gateway Dr',
  'borough': 'Brooklyn',
  'zipcode': '11239',
  'latitude': '40.65154222',
  'longitude': '-73.87262128'},
 {'dropoff_sitename': 'Staples',
  'address': '1885 Hylan Blvd',
  'borough': 'Staten Island',
  'zipcode': '10306',
  'latitude': '40.5838147',
  'longitude': '-74.0962032'},
 {'dropoff_sitename': 'Apple Store',
  'address': '90-15 Queens Blvd',
  'borough': 'Queens',
  'zipcode': '11373',
  'latitude': '40.734566',
  'longitude': '-73.870652'},
 {'dropoff_sitename': 'Goodwill',
  'address': '103 W 25 St',
  'borough': 'Manhattan',
  'zipcode': '10001',
  'latitude': '40.7444737',
  'longitude': '-73.9921732'},
 {'dropoff_sitename': 'Apple Store',
  'address': '247 Bedford Ave',
  'borough': 'Brooklyn',
  'zipcode': '11211',
  'latitude': '40.71561',
  'longitude': '-73.959746'},
 {'dropoff_sitename': 'WALTER',
  'address': '138 Hinsdale St',
  'borough': 'Brooklyn',
  'zipcode': '11207',
  'latitude': '40.67227998',
  'longitude': '-73.90107948'},
 {'dropoff_sitename': 'Best Buy',
  'address': '531 5th Ave',
  'borough': 'Manhattan',
  'zipcode': '10017',
  'latitude': '40.75483614',
  'longitude': '-73.97963772'},
 {'dropoff_sitename': 'Staples',
  'address': '800 Third Ave',
  'borough': 'Manhattan',
  'zipcode': '10022',
  'latitude': '40.75570567',
  'longitude': '-73.97138626'},
 {'dropoff_sitename': 'Goodwill',
  'address': '1114 1 Ave',
  'borough': 'Manhattan',
  'zipcode': '10065',
  'latitude': '40.760863',
  'longitude': '-73.960668'},
 {'dropoff_sitename': 'Apple Store',
  'address': '767 5 Ave',
  'borough': 'Manhattan',
  'zipcode': '10153',
  'latitude': '40.763609',
  'longitude': '-73.972435'},
 {'dropoff_sitename': 'Green Chip, Inc.',
  'address': '540 Kingland Ave',
  'borough': 'Brooklyn',
  'zipcode': '11222',
  'latitude': '40.73570942',
  'longitude': '-73.94439373'},
 {'dropoff_sitename': 'Staples',
  'address': '2040 White Plains Rd',
  'borough': 'Bronx',
  'zipcode': '10462',
  'latitude': '40.85207672',
  'longitude': '-73.86737946'},
 {'dropoff_sitename': 'Salvation Army',
  'address': '536 W 46 St',
  'borough': 'Manhattan',
  'zipcode': '10036',
  'latitude': '40.762665',
  'longitude': '-73.995377'},
 {'dropoff_sitename': 'Best Buy',
  'address': '8801 Queens Blvd',
  'borough': 'Queens',
  'zipcode': '11373',
  'latitude': '40.7357438',
  'longitude': '-73.87448827'},
 {'dropoff_sitename': 'Staples',
  'address': '330-340 Baychester Ave',
  'borough': 'Bronx',
  'zipcode': '10475',
  'latitude': '40.86768776',
  'longitude': '-73.82893736'},
 {'dropoff_sitename': 'Staples',
  'address': '1280 Lexington Ave',
  'borough': 'Manhattan',
  'zipcode': '10028',
  'latitude': '40.7798872',
  'longitude': '-73.9557037'},
 {'dropoff_sitename': 'Apple Store',
  'address': '185 Greenwich St',
  'borough': 'Manhattan',
  'zipcode': '10007',
  'latitude': '40.711639',
  'longitude': '-74.012343'},
 {'dropoff_sitename': 'DSNY Special Waste Drop-Off Site',
  'address': '12015 31 Ave',
  'borough': 'Queens',
  'zipcode': '11354',
  'latitude': '40.77123',
  'longitude': '-73.84757'},
 {'dropoff_sitename': 'Scrap King Greenpoint, LLC',
  'address': '374 Greenpoint Ave',
  'borough': 'Brooklyn',
  'zipcode': '11222',
  'latitude': '40.7318987',
  'longitude': '-73.9443865'},
 {'dropoff_sitename': 'Staples',
  'address': '641 6 Ave',
  'borough': 'Manhattan',
  'zipcode': '10011',
  'latitude': '40.7407266',
  'longitude': '-73.9948313'},
 {'dropoff_sitename': 'Irving Rubber & Metal Co',
  'address': '9525 Ditmas Ave',
  'borough': 'Brooklyn',
  'zipcode': '11236',
  'latitude': '40.65102651',
  'longitude': '-73.91076274'},
 {'dropoff_sitename': 'Best Buy',
  'address': '402 E Fordham Rd',
  'borough': 'Bronx',
  'zipcode': '10458',
  'latitude': '40.86087263',
  'longitude': '-73.89167099'},
 {'dropoff_sitename': 'Scrap King USA Inc',
  'address': '99 19th St',
  'borough': 'Brooklyn',
  'zipcode': '11232',
  'latitude': '40.6655837',
  'longitude': '-73.9970059'},
 {'dropoff_sitename': 'Staples',
  'address': '535 Morgan Ave',
  'borough': 'Brooklyn',
  'zipcode': '11222',
  'latitude': '40.72230119',
  'longitude': '-73.93917165'},
 {'dropoff_sitename': 'Salvation Army',
  'address': '2359 Jerome Ave',
  'borough': 'Bronx',
  'zipcode': '10468',
  'latitude': '40.860358',
  'longitude': '-73.9030775'},
 {'dropoff_sitename': 'Best Buy',
  'address': '60 W 23 St',
  'borough': 'Manhattan',
  'zipcode': '10010',
  'latitude': '40.7423606',
  'longitude': '-73.9923849'},
 {'dropoff_sitename': 'T&T Scrap, LLC',
  'address': '340 Maspeth Ave',
  'borough': 'Brooklyn',
  'zipcode': '11211',
  'latitude': '40.7180546',
  'longitude': '-73.9304626'},
 {'dropoff_sitename': 'Staples',
  'address': '1755 Broadway',
  'borough': 'Manhattan',
  'zipcode': '10019',
  'latitude': '40.766011',
  'longitude': '-73.98214997'},
 {'dropoff_sitename': 'Staples',
  'address': '105 W 125th St',
  'borough': 'Manhattan',
  'zipcode': '10027',
  'latitude': '40.80827765',
  'longitude': '-73.94594495'},
 {'dropoff_sitename': 'Salvation Army',
  'address': '493 Mosel Ave',
  'borough': 'Staten Island',
  'zipcode': '10304',
  'latitude': '40.60521855',
  'longitude': '-74.0838506'},
 {'dropoff_sitename': 'DSNY Special Waste Drop-Off Site',
  'address': '2 Farragut St',
  'borough': 'Bronx',
  'zipcode': '10474',
  'latitude': '40.801686',
  'longitude': '-73.87343'},
 {'dropoff_sitename': 'Staples',
  'address': '442 5th Ave',
  'borough': 'Manhattan',
  'zipcode': '10018',
  'latitude': '40.75198',
  'longitude': '-73.9824833'},
 {'dropoff_sitename': 'Staples',
  'address': '2892 Ocean Ave',
  'borough': 'Brooklyn',
  'zipcode': '11235',
  'latitude': '40.5908736',
  'longitude': '-73.9503307'},
 {'dropoff_sitename': 'Salvation Army',
  'address': '1294 Southern Blvd',
  'borough': 'Bronx',
  'zipcode': '10459',
  'latitude': '40.8306088',
  'longitude': '-73.891455'},
 {'dropoff_sitename': 'Goodwill',
  'address': '1704 2 Ave',
  'borough': 'Manhattan',
  'zipcode': '10128',
  'latitude': '40.7793',
  'longitude': '-73.950294'},
 {'dropoff_sitename': 'Staples',
  'address': '209-34 Northern Blvd',
  'borough': 'Queens',
  'zipcode': '11361',
  'latitude': '40.75909625',
  'longitude': '-73.77302777'},
 {'dropoff_sitename': 'Best Buy',
  'address': '622 Broadway',
  'borough': 'Manhattan',
  'zipcode': '10012',
  'latitude': '40.7258471',
  'longitude': '-73.99621957'},
 {'dropoff_sitename': 'Staples',
  'address': '5680 Broadway',
  'borough': 'Bronx',
  'zipcode': '10463',
  'latitude': '40.88108777',
  'longitude': '-73.90227651'},
 {'dropoff_sitename': 'Goodwill',
  'address': '7 W 14 St',
  'borough': 'Manhattan',
  'zipcode': '10011',
  'latitude': '40.736697',
  'longitude': '-73.994165'},
 {'dropoff_sitename': 'PASCAP Co., Inc.',
  'address': '4250 Boston Rd',
  'borough': 'Bronx',
  'zipcode': '10475',
  'latitude': '40.8882201',
  'longitude': '-73.8225387'},
 {'dropoff_sitename': 'Apple Store',
  'address': '45 Grand Central Terminal',
  'borough': 'Manhattan',
  'zipcode': '10017',
  'latitude': '40.752642',
  'longitude': '-73.977279'},
 {'dropoff_sitename': 'Best Buy',
  'address': '13107 40th Rd',
  'borough': 'Queens',
  'zipcode': '11354',
  'latitude': '40.75636718',
  'longitude': '-73.83696215'},
 {'dropoff_sitename': 'Best Buy',
  'address': '5001 Northern Blvd',
  'borough': 'Queens',
  'zipcode': '11101',
  'latitude': '40.75370894',
  'longitude': '-73.9117397'},
 {'dropoff_sitename': 'Staples',
  'address': '769 Broadway',
  'borough': 'Manhattan',
  'zipcode': '10003',
  'latitude': '40.73105907',
  'longitude': '-73.99228685'},
 {'dropoff_sitename': 'Salvation Army',
  'address': '4109 Park Ave',
  'borough': 'Bronx',
  'zipcode': '10457',
  'latitude': '40.845553',
  'longitude': '-73.901079'},
 {'dropoff_sitename': 'Salvation Army',
  'address': '208 E 23 St',
  'borough': 'Manhattan',
  'zipcode': '10010',
  'latitude': '40.738365',
  'longitude': '-73.9824462'},
 {'dropoff_sitename': 'Gershow Recycling of Brooklyn Inc',
  'address': '1188 Pitkin Ave',
  'borough': 'Brooklyn',
  'zipcode': '11212',
  'latitude': '40.67748108',
  'longitude': '-73.90292646'},
 {'dropoff_sitename': 'Apple Store',
  'address': '1981 Broadway',
  'borough': 'Manhattan',
  'zipcode': '10023',
  'latitude': '40.775064',
  'longitude': '-73.982637'},
 {'dropoff_sitename': 'DSNY Special Waste Drop-Off Site',
  'address': '1000 West Service Rd',
  'borough': 'Staten Island',
  'zipcode': '10312',
  'latitude': '40.56899487',
  'longitude': '-74.19338812'},
 {'dropoff_sitename': 'Staples',
  'address': '9319 5 Ave',
  'borough': 'Brooklyn',
  'zipcode': '11209',
  'latitude': '40.6166088',
  'longitude': '-74.0300263'},
 {'dropoff_sitename': 'Best Buy',
  'address': '171 W 230th St, Ste. 103',
  'borough': 'Bronx',
  'zipcode': '10463',
  'latitude': '40.87728015',
  'longitude': '-73.90491584'},
 {'dropoff_sitename': 'Sims Metal Management East',
  'address': '850 Edgewater Rd',
  'borough': 'Bronx',
  'zipcode': '10474',
  'latitude': '40.8184516',
  'longitude': '-73.8832997'},
 {'dropoff_sitename': 'Salvation Army',
  'address': '109 2nd Ave',
  'borough': 'Brooklyn',
  'zipcode': '11215',
  'latitude': '40.67144018',
  'longitude': '-73.9942085'},
 {'dropoff_sitename': 'DSNY Special Waste Drop-Off Site',
  'address': '459 N Henry St',
  'borough': 'Brooklyn',
  'zipcode': '11222',
  'latitude': '40.73476',
  'longitude': '-73.94543'},
 {'dropoff_sitename': 'Staples',
  'address': '4320 Broadway',
  'borough': 'Manhattan',
  'zipcode': '10033',
  'latitude': '40.852234',
  'longitude': '-73.934259'},
 {'dropoff_sitename': 'Allocco Recycling, Ltd.',
  'address': '540 Kingsland Ave',
  'borough': 'Brooklyn',
  'zipcode': '11222',
  'latitude': '40.7355308',
  'longitude': '-73.9443812'},
 {'dropoff_sitename': 'Micro Center',
  'address': '71-43 Kissena Blvd (Between 71st and 72nd Aves)',
  'borough': 'Queens',
  'zipcode': '11367',
  'latitude': '40.728866',
  'longitude': '-73.8150369'},
 {'dropoff_sitename': 'Big Reuse',
  'address': '1 12th St',
  'borough': 'Brooklyn',
  'zipcode': '11215',
  'latitude': '40.6722888',
  'longitude': '-73.9971998'},
 {'dropoff_sitename': 'Staples',
  'address': '5 Union Square West',
  'borough': 'Manhattan',
  'zipcode': '10003',
  'latitude': '40.73578828',
  'longitude': '-73.99179116'},
 {'dropoff_sitename': 'Staples',
  'address': '1760 Utica Ave',
  'borough': 'Brooklyn',
  'zipcode': '11234',
  'latitude': '40.62921082',
  'longitude': '-73.92835207'},
 {'dropoff_sitename': 'Staples',
  'address': '58-12 Queens Blvd',
  'borough': 'Queens',
  'zipcode': '11377',
  'latitude': '40.74128698',
  'longitude': '-73.9070244'},
 {'dropoff_sitename': 'Best Buy',
  'address': '610 Exterior St',
  'borough': 'Bronx',
  'zipcode': '10451',
  'latitude': '40.82153924',
  'longitude': '-73.92977867'},
 {'dropoff_sitename': 'Salvation Army',
  'address': '2053 Clove Rd',
  'borough': 'Staten Island',
  'zipcode': '10304',
  'latitude': '40.605057',
  'longitude': '-74.083695'},
 {'dropoff_sitename': 'PTK Restorations LLC',
  'address': '59-20 Grand Ave',
  'borough': 'Queens',
  'zipcode': '11378',
  'latitude': '40.720542',
  'longitude': '-73.907551'},
 {'dropoff_sitename': 'Apple Store',
  'address': '401 W 14 St',
  'borough': 'Manhattan',
  'zipcode': '10014',
  'latitude': '40.741335',
  'longitude': '-74.00555'},
 {'dropoff_sitename': 'Salvation Army',
  'address': '3911 61 St',
  'borough': 'Queens',
  'zipcode': '11377',
  'latitude': '40.746743',
  'longitude': '-73.9026954'},
 {'dropoff_sitename': 'Staples',
  'address': '2248 Broadway',
  'borough': 'Manhattan',
  'zipcode': '10024',
  'latitude': '40.7848159',
  'longitude': '-73.9788032'},
 {'dropoff_sitename': 'Goodwill',
  'address': '4747 Van Dam St',
  'borough': 'Queens',
  'zipcode': '11101',
  'latitude': '40.7415286',
  'longitude': '-73.9337864'},
 {'dropoff_sitename': 'Staples',
  'address': '2535 Richmond Ave',
  'borough': 'Staten Island',
  'zipcode': '10314',
  'latitude': '40.58605531',
  'longitude': '-74.16669338'},
 {'dropoff_sitename': 'Staples',
  'address': '675 3 Ave',
  'borough': 'Manhattan',
  'zipcode': '10017',
  'latitude': '40.7509006',
  'longitude': '-73.973911'},
 {'dropoff_sitename': 'Best Buy',
  'address': '52 E 14th St',
  'borough': 'Manhattan',
  'zipcode': '10003',
  'latitude': '40.73451587',
  'longitude': '-73.99052633'},
 {'dropoff_sitename': 'Goodwill',
  'address': '2231 3 Ave',
  'borough': 'Manhattan',
  'zipcode': '10035',
  'latitude': '40.801328',
  'longitude': '-73.937068'},
 {'dropoff_sitename': 'Best Buy',
  'address': '1280 Lexington Ave',
  'borough': 'Manhattan',
  'zipcode': '10028',
  'latitude': '40.7798872',
  'longitude': '-73.9557037'},
 {'dropoff_sitename': 'Scholes St Recycling Corp',
  'address': '492 Scholes St',
  'borough': 'Brooklyn',
  'zipcode': '11237',
  'latitude': '40.71123455',
  'longitude': '-73.92767114'},
 {'dropoff_sitename': 'Staples',
  'address': '1880 Coney Island Ave',
  'borough': 'Brooklyn',
  'zipcode': '11230',
  'latitude': '40.6118064',
  'longitude': '-73.9630824'},
 {'dropoff_sitename': 'Micro Center',
  'address': '850 3rd Ave (31st & 3rd Ave)',
  'borough': 'Brooklyn',
  'zipcode': '11232',
  'latitude': '40.6588044',
  'longitude': '-74.003448'},
 {'dropoff_sitename': 'Staples',
  'address': '409 Gateway Dr',
  'borough': 'Brooklyn',
  'zipcode': '11239',
  'latitude': '40.6539242',
  'longitude': '-73.8732584'},
 {'dropoff_sitename': 'Staples',
  'address': '93-18 Roosevelt Ave',
  'borough': 'Queens',
  'zipcode': '11372',
  'latitude': '40.74868912',
  'longitude': '-73.87263634'},
 {'dropoff_sitename': 'Best Buy',
  'address': '2795 Richmond Ave',
  'borough': 'Staten Island',
  'zipcode': '10314',
  'latitude': '40.57695637',
  'longitude': '-74.16738911'},
 {'dropoff_sitename': 'Apple Store',
  'address': '103 Prince St',
  'borough': 'Manhattan',
  'zipcode': '10012',
  'latitude': '40.725117',
  'longitude': '-73.998979'},
 {'dropoff_sitename': 'Salvation Army',
  'address': '4109 Park Ave',
  'borough': 'Bronx',
  'zipcode': '10457',
  'latitude': '40.84559331',
  'longitude': '-73.90103116'},
 {'dropoff_sitename': 'Staples',
  'address': '500 8 Ave',
  'borough': 'Manhattan',
  'zipcode': '10018',
  'latitude': '40.7530426',
  'longitude': '-73.9924445'},
 {'dropoff_sitename': 'Best Buy',
  'address': '625 Atlantic Ave',
  'borough': 'Brooklyn',
  'zipcode': '11217',
  'latitude': '40.6840997',
  'longitude': '-73.97548098'},
 {'dropoff_sitename': 'DSNY Special Waste Drop-Off Site',
  'address': '74 Pike Slip',
  'borough': 'Manhattan',
  'zipcode': '10002',
  'latitude': '40.71066',
  'longitude': '-73.99288'},
 {'dropoff_sitename': 'Apple Store',
  'address': '200 Baychester Avenue',
  'borough': 'Bronx',
  'zipcode': '10475',
  'latitude': '40.8638',
  'longitude': '-73.8278'},
 {'dropoff_sitename': 'Apple Store',
  'address': '940 Madison Ave',
  'borough': 'Manhattan',
  'zipcode': '10021',
  'latitude': '40.773375',
  'longitude': '-73.964538'},
 {'dropoff_sitename': 'Lumens',
  'address': '106-15 Sutphin Blvd',
  'borough': 'Queens',
  'zipcode': '11435',
  'latitude': '40.6948931',
  'longitude': '-73.8023815'}]

In [7]:
for i in electronics:
    i['Category'] = 'Electronics'

In [9]:
import pandas as pd
data = electronics

dfE = pd.DataFrame(data)
dfE.index.name = 'Index'
dfE = dfE.rename(columns={'dropoff_sitename': 'Sitename', 'address':'Address', 'borough': 'Borough' , 'zipcode':'Zip' , 'latitude':'Latitude', 'longitude':'Longitude', 'acceptedMaterials':'Category'})

dfE.to_csv('electronics.csv', index=False)

dfE

,Sitename,Address,Borough,Zip,Latitude,Longitude,Category
Index,,,,,,,
0,Best Buy,8923 Bay Pkwy,Brooklyn,11214,40.59360561,-73.99907225,Electronics
1,Recycle Your Devices,1885 Victory Blvd,Staten Island,10314,40.61714326,-74.12507436,Electronics
2,WE Pickups LLC,432 Austin Place #408,Bronx,10455,40.8090356,-73.9053482,Electronics
3,Apple Store,2655 Richmond Ave,Staten Island,10314,40.58187,-74.165866,Electronics
4,Staples,90-30 Metropolitan Ave,Queens,11374,40.71103454,-73.85841309,Electronics
...,...,...,...,...,...,...,...
99,Best Buy,625 Atlantic Ave,Brooklyn,11217,40.6840997,-73.97548098,Electronics
100,DSNY Special Waste Drop-Off Site,74 Pike Slip,Manhattan,10002,40.71066,-73.99288,Electronics
101,Apple Store,200 Baychester Avenue,Bronx,10475,40.8638,-73.8278,Electronics
102,Apple Store,940 Madison Ave,Manhattan,10021,40.773375,-73.964538,Electronics
103,Lumens,106-15 Sutphin Blvd,Queens,11435,40.6948931,-73.8023815,Electronics

In [10]:
import folium

electronics_map = folium.Map(location=[dfE['Latitude'].astype(float).mean(), dfE['Longitude'].astype(float).mean()], zoom_start=10)
for Sitename, row in dfE.iterrows():
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=row['Address'],
        tooltip=row['Sitename']
    ).add_to(electronics_map)
        
electronics_map

In [11]:
base_url = 'https://data.cityofnewyork.us'
special = '/resource/242c-ru4i.json'
params = {
    "$select": "name, address, city, zip, point"
}

rSW = requests.get(base_url + special, params = params)

In [12]:
rSW

In [13]:
special_waste=rSW.json()

In [14]:
special_waste

[{'name': 'DSNY Special Waste Drop-Off Site',
  'address': '74 Pike Slip',
  'city': 'New York',
  'zip': '10002',
  'point': {'type': 'Point',
   'coordinates': [-73.9923233839406, 40.7099070059109]}},
 {'name': 'DSNY Special Waste Drop-Off Site',
  'address': '12015 31 Ave',
  'city': 'Flushing',
  'zip': '11354',
  'point': {'type': 'Point',
   'coordinates': [-73.8471494631926, 40.7710013528924]}},
 {'name': 'DSNY Special Waste Drop-Off Site',
  'address': '1000 West Service Rd',
  'city': 'Staten Island',
  'zip': '10312',
  'point': {'type': 'Point',
   'coordinates': [-74.1948192653765, 40.5701296240937]}},
 {'name': 'DSNY Special Waste Drop-Off Site',
  'address': '459 N Henry St',
  'city': 'Brooklyn',
  'zip': '11222',
  'point': {'type': 'Point',
   'coordinates': [-73.9461380535929, 40.7356555409138]}},
 {'name': 'DSNY Special Waste Drop-Off Site',
  'address': '2 Farragut St',
  'city': 'Bronx',
  'zip': '10474',
  'point': {'type': 'Point',
   'coordinates': [-73.8748588729107, 40.8030613598415]}}]

In [15]:
for i in special_waste:
    i['Category'] = 'Special Waste'
    i['Longitude'] = i['point']['coordinates'][0]
    i['Latitude'] = i['point']['coordinates'][1]
    del i['point']

In [16]:
data2 = special_waste

dfSW = pd.DataFrame(data2)
dfSW.index.name = 'Index'
dfSW = dfSW.rename(columns={'name': 'Sitename', 'address':'Address', 'city': 'Borough' , 'zip':'Zip'})

dfSW.to_csv('special_waste.csv', index=False)

dfSW

,Sitename,Address,Borough,Zip,Category,Longitude,Latitude
Index,,,,,,,
0,DSNY Special Waste Drop-Off Site,74 Pike Slip,New York,10002,Special Waste,-73.992323,40.709907
1,DSNY Special Waste Drop-Off Site,12015 31 Ave,Flushing,11354,Special Waste,-73.847149,40.771001
2,DSNY Special Waste Drop-Off Site,1000 West Service Rd,Staten Island,10312,Special Waste,-74.194819,40.570130
3,DSNY Special Waste Drop-Off Site,459 N Henry St,Brooklyn,11222,Special Waste,-73.946138,40.735656
4,DSNY Special Waste Drop-Off Site,2 Farragut St,Bronx,10474,Special Waste,-73.874859,40.803061

In [17]:
special_waste_map = folium.Map(location=[dfSW['Latitude'].astype(float).mean(), dfSW['Longitude'].astype(float).mean()], zoom_start=10)
for Sitename, row in dfSW.iterrows():
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=row['Address'],
        tooltip=row['Sitename']
    ).add_to(special_waste_map)
    
special_waste_map

In [18]:
base_url = 'https://data.cityofnewyork.us'
pharma = '/resource/edk2-vkjh.json'
params = {
    "$select": "sitename, address, borough, zipcode, latitude, longitude"
}

rP = requests.get(base_url + pharma, params = params)

In [19]:
rP

In [20]:
pharma = rP.json()

In [22]:
pharma

[{'sitename': 'Center for Nursing & Rehabilitation',
  'address': '520 Prospect Pl, Brooklyn, NY 11238',
  'borough': 'Brooklyn',
  'zipcode': '11238',
  'latitude': '40.675125',
  'longitude': '-73.959525'},
 {'sitename': 'Calvary Hospital Inc.',
  'address': '1740 Eastchester Rd, Bronx, NY 10461',
  'borough': 'Bronx',
  'zipcode': '10461',
  'latitude': '40.848179',
  'longitude': '-73.84401'},
 {'sitename': 'Bedford Center for Nursing and Rehabilitation',
  'address': '40 Heyward St Brooklyn, NY 11249',
  'borough': 'Brooklyn',
  'zipcode': '11249',
  'latitude': '40.700186',
  'longitude': '-73.958208'},
 {'sitename': 'Hollis Park Manor Nursing Home',
  'address': '19106 Hillside Ave, Hollis, NY 11423',
  'borough': 'Queens',
  'zipcode': '11423',
  'latitude': '40.715906',
  'longitude': '-73.770689'},
 {'sitename': 'Medicine Center Rx LLC',
  'address': '92 E 167th Street,  Bronx,  NY 10452',
  'borough': 'Bronx',
  'zipcode': '10452',
  'latitude': '40.834944',
  'longitude': '-73.9199'},
 {'sitename': 'VLV Med Pharmacy Inc',
  'address': '4085 Broadway,  Manhattan,  NY 10032',
  'borough': 'Manhattan',
  'zipcode': '10032',
  'latitude': '40.844324',
  'longitude': '-73.9394'},
 {'sitename': 'CVS Pharmacy',
  'address': '219-39 89th Ave,  Queens,  NY 11427',
  'borough': 'Queens',
  'zipcode': '11427',
  'latitude': '40.729579',
  'longitude': '-73.7434'},
 {'sitename': 'CFH Wards Island Medical Clinic',
  'address': '1 Wards Island, New York, NY 10035',
  'borough': 'Manhattan',
  'zipcode': '10035',
  'latitude': '40.802501',
  'longitude': '-73.930881'},
 {'sitename': 'St. Marys Hospital For Children',
  'address': '29-01 216th St, Bayside, NY 11360',
  'borough': 'Queens',
  'zipcode': '11360',
  'latitude': '40.776586',
  'longitude': '-73.768889'},
 {'sitename': 'Bensonhurst Center for Rehabilitation and Healthcare',
  'address': '1740 84 St Brooklyn, NY 11214',
  'borough': 'Brooklyn',
  'zipcode': '11214',
  'latitude': '40.609055',
  'longitude': '-74.002632'},
 {'sitename': 'Regal Heights Rehabilitation and Healthcare Center',
  'address': '70-5 35th Ave Jackson Heights, NY 11372',
  'borough': 'Queens',
  'zipcode': '11372',
  'latitude': '40.750844',
  'longitude': '-73.895165'},
 {'sitename': 'La Guardia Pharmacy',
  'address': '101-22 Astoria Boulevard,  Queens,  NY 11369',
  'borough': 'Queens',
  'zipcode': '11369',
  'latitude': '40.761389',
  'longitude': '-73.8675'},
 {'sitename': 'Duane Reade',
  'address': '1 Union Square South,  Manhattan,  NY 10003',
  'borough': 'Manhattan',
  'zipcode': '10003',
  'latitude': '40.734149',
  'longitude': '-73.9904'},
 {'sitename': 'Medicine Shoppe Pharmacy',
  'address': '1109 Coney Island Ave,  Brooklyn,  NY 11230',
  'borough': 'Brooklyn',
  'zipcode': '11230',
  'latitude': '40.63059',
  'longitude': '-73.9659'},
 {'sitename': 'Safe Horizon Streetwork Project Lower East Side',
  'address': '33 Essex St, New York, NY 10002',
  'borough': 'Manhattan',
  'zipcode': '10002',
  'latitude': '40.716063',
  'longitude': '-73.989812'},
 {'sitename': 'AIDS Center of Queens County',
  'address': '11-39 Foam Place, Far Rockaway, NY 11691',
  'borough': 'Queens',
  'zipcode': '11691',
  'latitude': '40.604768',
  'longitude': '-73.751438'},
 {'sitename': 'CVS Pharmacy',
  'address': '7960 Metropolitan Ave,  Queens,  NY 11379',
  'borough': 'Queens',
  'zipcode': '11379',
  'latitude': '40.713265',
  'longitude': '-73.8723'},
 {'sitename': 'Walgreens/Duane Reade',
  'address': '777 Avenue of the Americas,  Manhattan,  NY 10001',
  'borough': 'Manhattan',
  'zipcode': '10001',
  'latitude': '40.745257',
  'longitude': '-73.9915'},
 {'sitename': 'NYPD 120th Precinct',
  'address': '78 Richmond Terrace,  Staten Island,  NY 10301',
  'borough': 'Staten Island',
  'zipcode': '10301',
  'latitude': '40.644718',
  'longitude': '-74.0775'},
 {'sitename': 'Positive Health Project',
  'address': '301 W 37 St, New York, NY 10018',
  'borough': 'Manhattan',
  'zipcode': '10018',
  'latitude': '40.754304',
  'longitude': '-73.992337'},
 {'sitename': 'Bronx Park Rehabilitation & Nursing Center',
  'address': '3845 Carpenter Ave, Bronx, NY 10467',
  'borough': 'Bronx',
  'zipcode': '10467',
  'latitude': '40.885872',
  'longitude': '-73.86525'},
 {'sitename': 'New York City AIDS Housing Network',
  'address': '80 4th Ave Brooklyn, NY 11217',
  'borough': 'Brooklyn',
  'zipcode': '11217',
  'latitude': '40.682223',
  'longitude': '-73.980193'},
 {'sitename': 'Brookdale Hospital Medical Center',
  'address': '1 Brookdale Plz, Brooklyn, NY 11212',
  'borough': 'Brooklyn',
  'zipcode': '11212',
  'latitude': '40.655255',
  'longitude': '-73.912511'},
 {'sitename': 'Sheepshead Nursing & Rehabilitation Center',
  'address': '2840 Knapp St, Brooklyn, NY 11235',
  'borough': 'Brooklyn',
  'zipcode': '11235',
  'latitude': '40.585299',
  'longitude': '-73.931843'},
 {'sitename': 'Project Hospitality - Multi-Service Center',
  'address': '514 Bay St, Staten Island, NY, 10304',
  'borough': 'Staten Island',
  'zipcode': '10304',
  'latitude': '40.629414',
  'longitude': '-74.076904'},
 {'sitename': 'Jewish Home Lifecare, Harry and Jeanette Weinber Campus',
  'address': '100 W Kingsbridge Rd, Bronx, NY 10468',
  'borough': 'Bronx',
  'zipcode': '10468',
  'latitude': '40.868039',
  'longitude': '-73.902224'},
 {'sitename': 'Northern Manhattan Nursing Home Inc',
  'address': '116 E 125th St New York, NY 10035',
  'borough': 'Manhattan',
  'zipcode': '10035',
  'latitude': '40.804559',
  'longitude': '-73.938268'},
 {'sitename': 'Sure Drugs',
  'address': '312 Ralph Ave,  Brooklyn,  NY 11233',
  'borough': 'Brooklyn',
  'zipcode': '11233',
  'latitude': '40.678495',
  'longitude': '-73.9218'},
 {'sitename': 'Greenfield Pharmacy',
  'address': '1526 Cortelyou Rd,  Brooklyn,  NY 11226',
  'borough': 'Brooklyn',
  'zipcode': '11226',
  'latitude': '40.641277',
  'longitude': '-73.9636'},
 {'sitename': 'Community Care Pharmacy',
  'address': '2913 Surf Avenue,  Brooklyn,  NY 11224',
  'borough': 'Brooklyn',
  'zipcode': '11224',
  'latitude': '40.573193',
  'longitude': '-73.9954'},
 {'sitename': 'Manhattanville Health Care Center',
  'address': '311 W 231 St, Bronx, NY 10463',
  'borough': 'Bronx',
  'zipcode': '10463',
  'latitude': '40.881216',
  'longitude': '-73.90868'},
 {'sitename': 'Harlem United Community AIDS Services',
  'address': '290 Lenox Ave New York, NY 10027',
  'borough': 'Manhattan',
  'zipcode': '10027',
  'latitude': '40.807393',
  'longitude': '-73.945298'},
 {'sitename': 'Duane Reade',
  'address': '1498 York Ave,  Manhattan,  NY 10075',
  'borough': 'Manhattan',
  'zipcode': '10075',
  'latitude': '40.771572',
  'longitude': '-73.9499'},
 {'sitename': 'Planned Parenthood of NYC Project St Beat Mobile Van - Central Office',
  'address': '349 E 149 St, Bronx, NY 10451',
  'borough': 'Bronx',
  'zipcode': '10451',
  'latitude': '40.816861',
  'longitude': '-73.91971'},
 {'sitename': 'New York Presbyterian Hospital New York Weill Cornell Center',
  'address': '515 E 70 St, New York, NY 10021',
  'borough': 'Manhattan',
  'zipcode': '10021',
  'latitude': '40.765277',
  'longitude': '-73.953631'},
 {'sitename': 'Community Health Action of Staten Island - Wellness Center',
  'address': '380 Van Duzer St, Staten Island, NY, 10304',
  'borough': 'Staten Island',
  'zipcode': '10304',
  'latitude': '40.628869',
  'longitude': '-74.079944'},
 {'sitename': 'Fairview Nursing Care Center',
  'address': '69-70 Grand Central Pkwy, Forest Hills, NY 11375',
  'borough': 'Queens',
  'zipcode': '11375',
  'latitude': '40.724669',
  'longitude': '-73.838275'},
 {'sitename': 'Brookhaven Rehabilitation & Healthcare Center',
  'address': '250 Beach 17 St Far Rockaway, NY 11691',
  'borough': 'Queens',
  'zipcode': '11691',
  'latitude': '40.596438',
  'longitude': '-73.750681'},
 {'sitename': 'Sea View Hospital, Rehabilitation Center and Home',
  'address': '460 Brielle Ave, Staten Island, NY, 10314',
  'borough': 'Staten Island',
  'zipcode': '10314',
  'latitude': '40.592102',
  'longitude': '-74.130981'},
 {'sitename': 'Dr. Susan Smith Mckinny Nursing and Rehabilitation Center',
  'address': '594 Albany Ave, Brooklyn, NY 11203',
  'borough': 'Brooklyn',
  'zipcode': '11203',
  'latitude': '40.659711',
  'longitude': '-73.940204'},
 {'sitename': 'Community Health Action of Staten Island',
  'address': '56 Bay St, Staten Island, NY 10301',
  'borough': 'Staten Island',
  'zipcode': '10301',
  'latitude': '40.640694',
  'longitude': '-74.076035'},
 {'sitename': 'Amesterdam Nursing Home Corp',
  'address': '1060 Amsterdam Ave, New York, NY 10025',
  'borough': 'Manhattan',
  'zipcode': '10025',
  'latitude': '40.804668',
  'longitude': '-73.963281'},
 {'sitename': 'VIP Community Services - Prevention Center',
  'address': '591 E Tremont Ave, Bronx, NY 10457',
  'borough': 'Bronx',
  'zipcode': '10457',
  'latitude': '40.846733',
  'longitude': '-73.89357'},
 {'sitename': 'The Pavilion at Queens for Rehabilitation & Nursing',
  'address': '36-17 Parsons Blvd, Flushing, NY 11354',
  'borough': 'Queens',
  'zipcode': '11354',
  'latitude': '40.764207',
  'longitude': '-73.823061'},
 {'sitename': 'Katz Drugs',
  'address': '76 Graham Ave,  Brooklyn,  NY 11206',
  'borough': 'Brooklyn',
  'zipcode': '11206',
  'latitude': '40.703608',
  'longitude': '-73.9423'},
 {'sitename': 'Walgreens',
  'address': '5564 Broadway,  Bronx,  NY 10463',
  'borough': 'Bronx',
  'zipcode': '10463',
  'latitude': '40.8782',
  'longitude': '-73.9044'},
 {'sitename': 'Schulman and Schachna Institute for Nursing and Rehabilitation',
  'address': '555 Rockaway Pkwy Brooklyn, NY 11212',
  'borough': 'Brooklyn',
  'zipcode': '11212',
  'latitude': '40.655575',
  'longitude': '-73.913361'},
 {'sitename': 'Bayside Pharmacy Inc',
  'address': '221-36 Horace Harding Expressway,  Queens,  NY 11364',
  'borough': 'Queens',
  'zipcode': '11364',
  'latitude': '40.749022',
  'longitude': '-73.7554'},
 {'sitename': 'Duane Reade',
  'address': '296 Flatbush Ave,  Brooklyn,  NY 11217',
  'borough': 'Brooklyn',
  'zipcode': '11217',
  'latitude': '40.678101',
  'longitude': '-73.9735'},
 {'sitename': 'Bay Park Center for Nursing and Rehabilitation',
  'address': '801 Co-op City Blvd, Bronx, NY, 10475',
  'borough': 'Bronx',
  'zipcode': '10475',
  'latitude': '40.879676',
  'longitude': '-73.829187'},
 {'sitename': 'NYPD 62nd Precinct',
  'address': '1925 Bath Ave,  Brooklyn,  NY 11214',
  'borough': 'Brooklyn',
  'zipcode': '11214',
  'latitude': '40.60259',
  'longitude': '-74.0031'},
 {'sitename': 'Jeanne Jugan Residence',
  'address': '2999 Schurz Ave, Bronx, NY 10465',
  'borough': 'Bronx',
  'zipcode': '10465',
  'latitude': '40.815298',
  'longitude': '-73.812744'},
 {'sitename': 'Walgreens/Duane Reade',
  'address': '1657 Broadway,  Manhattan,  NY 10019',
  'borough': 'Manhattan',
  'zipcode': '10019',
  'latitude': '40.762518',
  'longitude': '-73.9837'},
 {'sitename': 'New York Presbyterian Hospital Columbia Presbyterian Center',
  'address': '622 W 168th St New York, NY 10032',
  'borough': 'Manhattan',
  'zipcode': '10032',
  'latitude': '40.841041',
  'longitude': '-73.941319'},
 {'sitename': 'My Hope Pharmacy LLC',
  'address': '14114 Northern Boulevard,  Queens,  NY 11354',
  'borough': 'Queens',
  'zipcode': '11354',
  'latitude': '40.764143',
  'longitude': '-73.8251'},
 {'sitename': 'Maimonides Medical Center',
  'address': '4802 10 Ave, Brooklyn, NY 11219',
  'borough': 'Brooklyn',
  'zipcode': '11219',
  'latitude': '40.639716',
  'longitude': '-73.999084'},
 {'sitename': 'Menorah Home & Hospital For Aged & Infirm',
  'address': '1516 Oriental Blvd, Brooklyn, NY 11235',
  'borough': 'Brooklyn',
  'zipcode': '11235',
  'latitude': '40.5766971',
  'longitude': '-73.937898'},
 {'sitename': 'Heritage Pharmacy',
  'address': '233 East Tremont Ave,  Bronx,  NY 10457',
  'borough': 'Bronx',
  'zipcode': '10457',
  'latitude': '40.848977',
  'longitude': '-73.9047'},
 {'sitename': 'NYPD 123rd Precinct',
  'address': '116 Main Street,  Staten Island,  NY 10307',
  'borough': 'Staten Island',
  'zipcode': '10307',
  'latitude': '40.511796',
  'longitude': '-74.25'},
 {'sitename': "BJ's Pharmacy",
  'address': '80 East 116th Street,  Manhattan,  NY 10029',
  'borough': 'Manhattan',
  'zipcode': '10029',
  'latitude': '40.80005077',
  'longitude': '-73.94389125'},
 {'sitename': 'AIDS Center of Queens County',
  'address': '161-21 Jamaica Ave, Jamaica, NY 11432',
  'borough': 'Queens',
  'zipcode': '11432',
  'latitude': '40.704394',
  'longitude': '-73.797905'},
 {'sitename': 'Queens Central Pharmacy, Inc',
  'address': '116-08 Queens Boulevard,  Queens,  NY 11375',
  'borough': 'Queens',
  'zipcode': '11375',
  'latitude': '40.715472',
  'longitude': '-73.8335'},
 {'sitename': 'Manor Haven Health Care Center',
  'address': '1441 Gateway Blvd, Far Rockaway, NY 11691',
  'borough': 'Queens',
  'zipcode': '11691',
  'latitude': '40.600666',
  'longitude': '-73.749779'},
 {'sitename': "CFH Susan's Place Medical Clinic",
  'address': '1912 Jerome Ave, Bronx, NY 10453',
  'borough': 'Bronx',
  'zipcode': '10453',
  'latitude': '40.850512',
  'longitude': '-73.9101'},
 {'sitename': 'CVS Pharmacy',
  'address': '31-01 Ditmars Boulevard,  Queens,  NY 11105',
  'borough': 'Queens',
  'zipcode': '11105',
  'latitude': '40.776288',
  'longitude': '-73.9101'},
 {'sitename': 'Kings Harbor Multicare Center',
  'address': '2000 E Gun Hill Rd, Bronx, NY 10469',
  'borough': 'Bronx',
  'zipcode': '10469',
  'latitude': '40.860302',
  'longitude': '-73.829885'},
 {'sitename': 'Duane Reade',
  'address': '136-02 Roosevelt Ave,  Queens,  NY 11354',
  'borough': 'Queens',
  'zipcode': '11354',
  'latitude': '40.759402',
  'longitude': '-73.8297'},
 {'sitename': 'NYPD 72nd Precinct',
  'address': '830 4th Ave,  Brooklyn,  NY 11232',
  'borough': 'Brooklyn',
  'zipcode': '11232',
  'latitude': '40.658186',
  'longitude': '-74.001'},
 {'sitename': "CFH Saint John's Medical Clinic",
  'address': '795 Lexington Ave, Brooklyn, NY 11221',
  'borough': 'Brooklyn',
  'zipcode': '11221',
  'latitude': '40.690319',
  'longitude': '-73.92892'},
 {'sitename': 'Ozanam Hall of Queens Nursing Home',
  'address': '42-41 201st St, Bayside, NY 11361',
  'borough': 'Queens',
  'zipcode': '11361',
  'latitude': '40.758658',
  'longitude': '-73.782468'},
 {'sitename': 'CFH Bushwick Medical Clinic',
  'address': '1675 Broadway, Brooklyn, NY 11207',
  'borough': 'Brooklyn',
  'zipcode': '11207',
  'latitude': '40.684433',
  'longitude': '-73.91243'},
 {'sitename': 'Queens Boulevard Extended Care Facility',
  'address': '61-11 Queens Blvd, Woodside, NY 11377',
  'borough': 'Queens',
  'zipcode': '11377',
  'latitude': '40.741631',
  'longitude': '-73.903036'},
 {'sitename': 'Modern Pharmacy',
  'address': '95-02 Van Wyck Expressway,  Queens,  NY 11419',
  'borough': 'Queens',
  'zipcode': '11419',
  'latitude': '40.696061',
  'longitude': '-73.8136'},
 {'sitename': 'Alliance for Positive Change - Midtown Central location',
  'address': '64 W 35th St 3rd Fl, New York, NY 10001',
  'borough': 'Manhattan',
  'zipcode': '10001',
  'latitude': '40.75009',
  'longitude': '-73.986665'},
 {'sitename': 'CVS Pharmacy',
  'address': '630 Lexington Ave,  Manhattan,  NY 10002',
  'borough': 'Manhattan',
  'zipcode': '10002',
  'latitude': '40.759005',
  'longitude': '-73.9715'},
 {'sitename': 'Flatbush Rx Pharmacy',
  'address': '1855 Flatbush Ave,  Brooklyn,  NY 11210',
  'borough': 'Brooklyn',
  'zipcode': '11210',
  'latitude': '40.62177114',
  'longitude': '-73.96497705'},
 {'sitename': 'Providence Rest, Inc',
  'address': '3304 Waterbury Ave, Bronx, NY 10465',
  'borough': 'Bronx',
  'zipcode': '10465',
  'latitude': '40.834988',
  'longitude': '-73.817602'},
 {'sitename': 'CVS Pharmacy',
  'address': '1361 Hylan Boulevard,  Staten Island,  NY 10305',
  'borough': 'Staten Island',
  'zipcode': '10305',
  'latitude': '40.595467',
  'longitude': '-74.0865'},
 {'sitename': '13th Ave Pharmacy',
  'address': '5211 13th Ave,  Brooklyn,  NY 11219',
  'borough': 'Brooklyn',
  'zipcode': '11219',
  'latitude': '40.632953',
  'longitude': '-73.9939'},
 {'sitename': 'Ballard Pharmacy',
  'address': '226 Prospect Park West,  Brooklyn,  NY 11215',
  'borough': 'Brooklyn',
  'zipcode': '11215',
  'latitude': '40.659998',
  'longitude': '-73.981'},
 {'sitename': 'S&M Pharmacy',
  'address': '6850 Main Street,  Queens,  NY 11367',
  'borough': 'Queens',
  'zipcode': '11367',
  'latitude': '40.732373',
  'longitude': '-73.8253'},
 {'sitename': 'New East Side Nursing Home',
  'address': '25 Willett St, New York, NY 10002',
  'borough': 'Manhattan',
  'zipcode': '10002',
  'latitude': '40.71707239',
  'longitude': '-73.98262391'},
 {'sitename': 'Ami Pharmacy DBA St. Jesus Pharmacy',
  'address': '4180 Broadway,  Manhattan,  NY 10033',
  'borough': 'Manhattan',
  'zipcode': '10033',
  'latitude': '40.847781',
  'longitude': '-73.9376'},
 {'sitename': 'Workmens Circle Multicare Center',
  'address': '3155 Grace Ave, Bronx, NY, 10469',
  'borough': 'Bronx',
  'zipcode': '10469',
  'latitude': '40.874247',
  'longitude': '-73.837423'},
 {'sitename': 'Midway Nursing Home',
  'address': '6995 Queens Midtown Expy Maspeth, NY 11378',
  'borough': 'Queens',
  'zipcode': '11378',
  'latitude': '40.726424',
  'longitude': '-73.890761'},
 {'sitename': 'New London Pharmacy, Inc',
  'address': '246 8th Ave,  Manhattan,  NY 10011',
  'borough': 'Manhattan',
  'zipcode': '10011',
  'latitude': '40.744868',
  'longitude': '-73.9984'},
 {'sitename': 'Parker Jewish Intitute For Healthcare and Rehab',
  'address': '271-11 76th Ave, Glen Oaks, NY 11004',
  'borough': 'Queens',
  'zipcode': '11004',
  'latitude': '40.755618',
  'longitude': '-73.707472'},
 {'sitename': 'Walgreens',
  'address': '1551 Richmond Ave,  Staten Island,  NY 10314',
  'borough': 'Staten Island',
  'zipcode': '10314',
  'latitude': '40.610328',
  'longitude': '-74.1602'},
 {'sitename': 'Comfort Drugs',
  'address': '13523 Roosevelt Ave,  Queens,  NY 11354',
  'borough': 'Queens',
  'zipcode': '11354',
  'latitude': '40.759448',
  'longitude': '-73.8311'},
 {'sitename': 'Hillside Manor Rehab & Extended Care Center',
  'address': '182-15 Hillside Ave, Queens, NY 11432',
  'borough': 'Queens',
  'zipcode': '11432',
  'latitude': '40.713859',
  'longitude': '-73.780149'},
 {'sitename': 'CVS Pharmacy',
  'address': '3775 E. Tremont Ave,  Bronx,  NY 10465',
  'borough': 'Bronx',
  'zipcode': '10465',
  'latitude': '40.825717',
  'longitude': '-73.8205'},
 {'sitename': 'Kenby Pharmacy',
  'address': '6024 5th Ave,  Brooklyn,  NY 11220',
  'borough': 'Brooklyn',
  'zipcode': '11220',
  'latitude': '40.639144',
  'longitude': '-74.0169'},
 {'sitename': 'Walgreens/Duane Reade',
  'address': '773 Lexington Ave,  Manhattan,  NY 10065',
  'borough': 'Manhattan',
  'zipcode': '10065',
  'latitude': '40.763135',
  'longitude': '-73.967'},
 {'sitename': 'Greater Harlem Nursing Home Company',
  'address': '30 W 138th St, New York, NY 10037',
  'borough': 'Manhattan',
  'zipcode': '10037',
  'latitude': '40.814981',
  'longitude': '-73.937562'},
 {'sitename': 'Hundson Pointe at Riverdale Center for Nursing and Rehabilitation',
  'address': '3220 Henry Hudson Pkwy, Bronx, NY 10463',
  'borough': 'Bronx',
  'zipcode': '10463',
  'latitude': '40.884693',
  'longitude': '-73.913918'},
 {'sitename': 'Bridging Access to Care',
  'address': '2261 Church Ave, Brooklyn, NY 11226',
  'borough': 'Brooklyn',
  'zipcode': '11226',
  'latitude': '40.6509',
  'longitude': '-73.956804'},
 {'sitename': 'New York Ave Pharmacy',
  'address': '3424 Church Ave,  Brooklyn,  NY 11203',
  'borough': 'Brooklyn',
  'zipcode': '11203',
  'latitude': '40.650789',
  'longitude': '-73.9449'},
 {'sitename': 'Jack D. Weiler Hospital of the Albert Einstein College of Medicine',
  'address': '1825 Eastchester Rd, Bronx, NY 10461',
  'borough': 'Bronx',
  'zipcode': '10461',

In [28]:
for i in pharma:
    i['Category'] = 'Pharmaceuticals & Syringes'

In [23]:
data3 = pharma

dfP = pd.DataFrame(data3)
dfP.index.name = 'Index'
dfP = dfP.rename(columns={'sitename': 'Sitename', 'address':'Address', 'borough': 'Borough' , 'zipcode':'Zip', 'latitude':'Latitude', 'longitude':'Longitude'})
    
dfP.to_csv('pharmaceuticals-syringes.csv', index=False)

dfP

,Sitename,Address,Borough,Zip,Latitude,Longitude
Index,,,,,,
0,Center for Nursing & Rehabilitation,"520 Prospect Pl, Brooklyn, NY 11238",Brooklyn,11238,40.675125,-73.959525
1,Calvary Hospital Inc.,"1740 Eastchester Rd, Bronx, NY 10461",Bronx,10461,40.848179,-73.84401
2,Bedford Center for Nursing and Rehabilitation,"40 Heyward St Brooklyn, NY 11249",Brooklyn,11249,40.700186,-73.958208
3,Hollis Park Manor Nursing Home,"19106 Hillside Ave, Hollis, NY 11423",Queens,11423,40.715906,-73.770689
4,Medicine Center Rx LLC,"92 E 167th Street, Bronx, NY 10452",Bronx,10452,40.834944,-73.9199
...,...,...,...,...,...,...
334,NYPD 70th Precinct,"154 Lawrence Ave, Brooklyn, NY 11230",Brooklyn,11230,40.630359,-73.9737
335,Sterling Pharmacy,"38-01 Bell Boulevard, Queens, NY 11361",Queens,11361,40.766455,-73.7722
336,Wellness Center Pharmacy,"40-13 Broadway, Queens, NY 11102",Queens,11102,40.758953,-73.9184
337,Cedars Pharmacy,"95-19 57th Avenue, Queens, NY 11373",Queens,11373,40.736972,-73.8653
338,Holliswood Center for Rehabilitation and Healt...,"195-44 Woodhull Ave, Hollis NY 11423",Queens,11423,40.712274,-73.763898

In [24]:
pharma_map = folium.Map(location=[dfP['Latitude'].astype(float).mean(), dfP['Longitude'].astype(float).mean()], zoom_start=10)
for Sitename, row in dfP.iterrows():
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=row['Address'],
        tooltip=row['Sitename']
    ).add_to(pharma_map)
    
pharma_map